# This is a basic workflow to help you get started with Actions

name: GITHUB CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main:
    name: BUILD AND TEST ON CI
    runs-on: ubuntu-18.04
    if: "contains(github.event.head_commit.message, 'build')"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        python-version: '3.7.4'
    # Runs a set of commands using the runners shell
    - name: Setup Python Dependencies and Lint
      run: |
        pip3 install -r requirements.txt
